### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by jayfk** [pyupio/changelogs#58]
Package: oursql3
```
>>> sync_changelog('oursql3')
Traceback (most recent call last):
  File "/app/pyupio/packages/tasks.py", line 228, in sync_changelog
    d['parsed_changelog'] = changelogs.get(name=name, functions=fns)
  File "/usr/local/lib/python3.6/site-packages/changelogs/changelogs.py", line 189, in get
    _depth=_depth+1)
  File "/usr/local/lib/python3.6/site-packages/changelogs/changelogs.py", line 177, in get
    get_head_fn=fns["get_head"]
  File "/usr/local/lib/python3.6/site-packages/changelogs/launchpad.py", line 79, in parse
    return {e["version"]: e["changelog"] for e in content["entries"]
TypeError: string indices must be integers
```

**Comment by jayfk** [comment]
This package seems to work now.
